name: gammapy-v1.0-paper

channels:
  - defaults
  - conda-forge

dependencies:
  - gammapy=0.19
  - numpy=1.21.1
  - matplotlib=3.5.1
  - pip>=20.3.3
  - python=3.9
  - astropy=5.0
  - latexindent.pl
  - pre-commit
  - rust
  - ruamel.yaml
  - pip:
      - pygments
