name: gammapy-v1.0-paper

channels:
  - defaults
  - conda-forge
  - bioconda

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - gammapy=0.19
  - iminuit=2.8.4
  - numpy=1.21.1
  - matplotlib=3.5.1
  - pip>=20.3.3
  - python=3.9
  - astropy=5.0
  - markupsafe=2.0.1
  - snakemake
  - jinja2
  - latexindent.pl
  - pre-commit
  - rust
  - ruamel.yaml
  - tqdm
  - requests
  - pip:
      - pygments
